In [1]:
import pandas as pd
import numpy as np
import datetime
from datetime import date

from sklearn.linear_model import LinearRegression

In [2]:
#speed to pace (and vis versa) conversion
def mins_to_meters(m, s):
    base10_sec = round(s/60, 3)
    base10_min = m+base10_sec
    seconds = base10_min*60
    metersps = 1609.34/seconds
    return metersps

def meters_to_mins(mps):
    sec_per_mile = round(1609.34/mps, 3)
    base10_min = sec_per_mile/60
    mins = int(base10_min)
    sec = round(base10_min%1, 3)*60
    return mins, sec

#create model for calculating athlete level
data = {'speed': [4.291573333333333, 5.109015873015872, 2.438393939393939, 2.682233333333333], 
        'distance': [26.2, 3.1, 26.2, 3.1],'level': [0, 0, 10, 10]}
df_pace_lvl = pd.DataFrame(data)

#calculate slope and intercept -linear
X = df_pace_lvl[['speed', 'distance']]
y = df_pace_lvl['level']
reg = LinearRegression().fit(X, y)
print('score: ', reg.score(X, y))
print('coefficients: ', reg.coef_)
print('intercept: ', reg.intercept_)

score:  0.9823553977865943
coefficients:  [-4.59048661 -0.10545023]
intercept:  23.209708290925104

In [3]:
#function to date race date, number of weeks to train, and generate 
def get_calendar(race_year, race_month, race_day, weeks, pace_min, pace_sec, distance):
    
    #calcluate meters per second (speed) from goal pace
    speed = mins_to_meters(m=pace_min, s=pace_sec)
    
    race_date = date(race_year, race_month, race_day+1)
    
    cal = weeks*7
    
    date_list = [race_date - datetime.timedelta(days=x) for x in range(1,(cal+1))]
    
    date_list.reverse()
    
    days = []

    for x in date_list:
        days.append(x.weekday())
        
    data = {'date': date_list, 'day_code': days}
    
    df_training_cal = pd.DataFrame(data)
    
    #create validation table for weekday codes/desc to join to training calendar
    weekdays = {'day_code': range(0,7), 'day_desc': ['Mon', 'Tues', 'Wed', 'Thurs', 'Fri', 'Sat', 'Sun']}
    df_weekdays = pd.DataFrame(weekdays)
    df_weekdays
    
    df_training_cal = pd.merge(df_training_cal, df_weekdays, how='left', on='day_code')
    
    #find first monday and crop calendar down to start on first monday
    first_mon = df_training_cal[df_training_cal.day_code == 0].index[0]
    df_training_cal = df_training_cal.iloc[first_mon:]
    
    #create column for week count
    week = []
    count = 0
    for index, row in df_training_cal.iterrows():
        if row.day_code == 0:
            count += 1
            week.append(count)
        else:
            week.append(count)
    df_training_cal['week']=week
    
    #create column for training phase
    #2 week taper for blocks under 14 weeks, 3 week taper for blocks >= 14 weeks
    block = 0
    if weeks < 14:
        block += (df_training_cal.week.max() - 2)
    if weeks >= 14:
        block += (df_training_cal.week.max() - 3)
    base = np.ceil(block*0.4)
    peak = np.floor(block*0.6)

    phase= []

    for index, row in df_training_cal.iterrows():
        if row.week <= base:
            phase.append('base')
        elif row.week-base <= peak:
            phase.append('peak')
        else:
            phase.append('taper')
    df_training_cal['phase']=phase
    
    #calculate level (get initial level and if out of range(0,10) then assign to closest level in level_final
    user_X = pd.DataFrame({'speed': [speed], 'distance': [distance]})
    level_initial = reg.predict(user_X)[0]
    level_final = []
    
    if level_initial < 0:
        level_final.append(0)
    elif level_initial > 10:
        level_final.append(10)
    else:
        level_final.append(level_initial)
    
    #weekly mileage peak
    mileage_max = 0
    if distance == 3.1:
        mileage_max += 45
    elif distance == 6.2:
        mileage_max += 50
    elif distance == 13.1:
        mileage_max += 60
    elif distance == 26.2:
        mileage_max += 75
    
    user_max = mileage_max-(level_final[0]*3)
    
    #weekly mileage
    base = len(df_training_cal.loc[df_training_cal.phase=='base'].week.unique())
    peak = len(df_training_cal.loc[df_training_cal.phase=='peak'].week.unique())
    taper = len(df_training_cal.loc[df_training_cal.phase=='taper'].week.unique())
    
    week_1 = round(user_max/3, 1)
    build = user_max-week_1
    weekly_miles = []
    
    week_num = []
    
    for index, row in df_training_cal.iterrows():
        if row.week not in week_num:
            week_num.append(row.week)
            
    weekly_miles = [week_1]
    miles = 0
    
    for i in range(1,base):
        miles += build/(base-1)
        weekly_miles.append(round(week_1+miles, 1))
    
    for i in range(1, peak+1):
        weekly_miles.append(round(user_max, 1))
    
    if taper == 2:
        weekly_miles.append(user_max*0.7)
        weekly_miles.append(user_max*0.4)
        
    if taper == 3:
        weekly_miles.append(round(user_max*0.85, 1))
        weekly_miles.append(round(user_max*0.65, 1))
        weekly_miles.append(round(user_max*0.3, 1))
    
    data = {'week': week_num, 'mileage': weekly_miles}
    df_mileage = pd.DataFrame(data)
    
    #add weekly mileage into df_training_cal
    weekly_mileage = []
    for index, row in df_training_cal.iterrows():
        weekly_mileage.append(df_mileage.loc[df_mileage.week == row.week].mileage.values[0])
    
    df_training_cal["weekly_mileage"] = weekly_mileage
    
    #add down week for training blocks >= 14 weeks
    if weeks >= 14:
        down_phase = []
        down_mileage = []
        
        for index, row in df_training_cal.iterrows():
            if row.week == (base + (peak-2)):
                down_phase.append('down')
                down_mileage.append(round(user_max*0.5, 1))
            else:
                down_phase.append(row.phase)
                down_mileage.append(row.weekly_mileage)
                
        df_training_cal['phase']=down_phase
        df_training_cal['weekly_mileage']=down_mileage
    
    return df_training_cal, level_final, level_initial, user_max, df_mileage

In [4]:
result = get_calendar(race_year=2023, race_month=11, race_day=19, weeks=16, pace_min=7, pace_sec=10, distance=26.2)
result[0]

           date  day_code day_desc  week  phase  weekly_mileage
0    2023-07-31         0      Mon     1   base            21.7
1    2023-08-01         1     Tues     1   base            21.7
2    2023-08-02         2      Wed     1   base            21.7
3    2023-08-03         3    Thurs     1   base            21.7
4    2023-08-04         4      Fri     1   base            21.7
..          ...       ...      ...   ...    ...             ...
107  2023-11-15         2      Wed    16  taper            19.6
108  2023-11-16         3    Thurs    16  taper            19.6
109  2023-11-17         4      Fri    16  taper            19.6
110  2023-11-18         5      Sat    16  taper            19.6
111  2023-11-19         6      Sun    16  taper            19.6

[112 rows x 6 columns]

In [5]:
result[0][['week', 'phase', 'weekly_mileage']].drop_duplicates()

     week  phase  weekly_mileage
0       1   base            21.7
7       2   base            30.4
14      3   base            39.1
21      4   base            47.8
28      5   base            56.5
35      6   base            65.2
42      7   peak            65.2
49      8   peak            65.2
56      9   peak            65.2
63     10   peak            65.2
70     11   down            32.6
77     12   peak            65.2
84     13   peak            65.2
91     14  taper            55.4
98     15  taper            42.4
105    16  taper            19.6